SELECT T1.ID, T1.GENOTYPE, T2.PARENT_GENOTYPE
FROM ECOLI_DATA T1
JOIN (
    SELECT ID, GENOTYPE AS PARENT_GENOTYPE
    FROM ECOLI_DATA
) T2 ON T1.PARENT_ID = T2.ID
WHERE T1.GENOTYPE & T2.PARENT_GENOTYPE = T2.PARENT_GENOTYPE
ORDER BY ID ASC;
